### ISSUE TITLE
Reformatting without tidy modifies / fixes error

### ISSUE THREAD

**Issue by edwinheij** [Stolz/laravel-html-tidy#2]
I only want to use reformatting (html source) without tidy, for example, removing empty attributes (with bootstrap I got a lot). It will mess up my layout. Is this possible?

**Comment by Stolz** [comment]
According to [this answer in SO](http://stackoverflow.com/questions/7151180/use-html-tidy-to-just-indent-html-code) it is not possible. You could use a set of config options to "repair" as low as possible and (mostly) only re-indent the html.

**Comment by edwinheij** [comment]
Thanks.  Will look into it.
