### ISSUE TITLE
Call to undefined function Stolz\HtmlTidy\str_contains() for laravel7

### ISSUE THREAD

**Issue by nepster-web** [Stolz/laravel-html-tidy#6]
![изображение](https://user-images.githubusercontent.com/5681979/77108602-2c719280-6a2b-11ea-96bd-49fb24665bbc.png)

Laravel docs say that the arr_ and str_ helpers are moved to a separate package called laravel/helpers.

https://github.com/Stolz/laravel-html-tidy/pull/5

**Comment by Stolz** [comment]
Thanks for reporting this. This should be fixed with the latest release
